### ISSUE TITLE
JoeyNMT on Google CoLab

### ISSUE THREAD

**Issue by bugwelle** [bugwelle/cl-neural-networks#2]
Erstmal:

 - Beispiel Projekt von JoeyNMT am Laufen kriegen, dies dokumentieren

Gegen Ende:

 - Unser Projekt trainieren

**Comment by bugwelle** [comment]
Stefan hat JoeyNMT in Colab laufen lassen. Das Juypter Notebook ist im Repo.

@stefanDeveloper Könntest du noch ein paar Links posten?

**Comment by stefanDeveloper** [comment]
Einmal [hier](https://github.com/bugwelle/cl-neural-networks/blob/main/colab/joeynmt.ipynb).
Zudem hat JoeyNMT selbst auch ein eigenes [Colar](https://github.com/joeynmt/joeynmt/blob/master/joey_demo.ipynb)
