### ISSUE TITLE
Speech datasets | Preprocessing | Setup / Implementierung

### ISSUE THREAD

**Issue by bugwelle** [bugwelle/cl-neural-networks#3]
Wir können <https://commonvoice.mozilla.org/en/datasets> verwenden. 

Fragen:

 - Wie sollen wir Daten verarbeitet werden? (preprocessing)
 - Welche Sprache nehmen wir? 
   - [x] German (26GB)
   - [ ] English (65GB)
 - Daten einteilen? Training, Test, Production,...
 - PyTorch für Audio: <https://pytorch.org/audio/stable/index.html>
   -  oder aber andere Bibliotheken verwenden?

Weitere Links:

 - https://opennmt.net/OpenNMT-py/legacy/speech2text.html

**Comment by ameyering** [comment]
Filterung von Robin umgesetzt. Länge auf 70 Zeichen erhöht, damit haben wir im Trainingsdatensatz jetzt über 7000 Einträge.

Vorverarbeitung enthält:

 - Lowercasing
 - Sätze mit Sonderzeichen entfernt
 - Nur männliche Stimme
 - Kein Akzent, ...

**Comment by bugwelle** [comment]
Filterung von Robin umgesetzt. Länge auf 70 Zeichen erhöht, damit haben wir im Trainingsdatensatz jetzt über 7000 Einträge.

Vorverarbeitung enthält:

 - Lowercasing
 - Sätze mit Sonderzeichen entfernt
 - Nur männliche Stimme
 - Kein Akzent, ...

**Comment by bugwelle** [comment]
PS: Die neue Trainingsdatei ist 250MB groß. Von vorher 30MB.
