### ISSUE TITLE
JoeyNMT Model für Speech Processing

### ISSUE THREAD

**Issue by bugwelle** [bugwelle/cl-neural-networks#7]
Erfordert #6 

JoeyNMT Model:

 -. kann auf existierendem Model aufbauen
 - evtl. `Speech2TextModel` oder ähnliches
 - Vorgehen:
   -  Copy&Paste von existierendem Model
   - Anpassung an unsere Daten (siehe #6)

**Comment by bugwelle** [comment]
Wir können das Model von SpeechJoey nehmen und dies natürlich auch so angeben. speechJoey selbst funktioniert nur so halb. Es müssen ältere Pakete installiert werden:

```
numpy
torch>=0.4.1,<=1.8.0
matplotlib
sacrebleu>=1.2.10,<2
seaborn
pyyaml>=5.1
subword-nmt
librosa
pylint
editdistance
tensorboardX
torchtext==0.6.0
```

**Comment by stefanDeveloper** [comment]
/ [ ] Issue bei [SpeechJoey](https://github.com/Sariyusha/speech_joey) erstellen
